name: medpal
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Intl
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Routing
  go_router: ^16.3.0

  # Local Persistency
  shared_preferences: ^2.5.3

  # State Management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  bloc_presentation: ^1.1.1

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.4

  # Plugins / Services
  image_picker: ^1.2.0

  # UI
  gap: ^3.0.1
  loader_overlay: ^5.0.0
  introduction_screen: ^4.0.0

  # General
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - shorebird.yaml
