name: medpal
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Intl
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Routing
  go_router: ^17.0.1

  # Local Persistency
  shared_preferences: ^2.5.4

  # State Management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  bloc_presentation: ^1.1.2

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # Plugins / Services
  image_picker: ^1.2.1

  # UI
  gap: ^3.0.1
  loader_overlay: ^5.0.0
  introduction_screen: ^4.0.0
  lottie: ^3.3.2
  intl_phone_number_input: ^0.7.5
  infinite_calendar_view: ^2.10.2

  # General
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  dart_code_linter: ^3.2.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/images/
    - shorebird.yaml
