name: MedPal CI/CD
env:
  FLUTTER_VERSION: 3.38.5

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality_checks:
    name: Quality Checks (Lint, Test, Coverage)
    runs-on: ubuntu-latest
    environment: Medpal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install cspell
        run: npm install -g cspell

      - name: Run Spell check
        run: ./scripts/quality/check-spelling.sh

      - name: Get dependencies
        run: flutter pub get

      - name: Copy dummy Firebase options for CI
        run: cp .github/ci/firebase_options.dart lib/firebase_options.dart

      - name: Run build_runner
        run: dart run build_runner build

      - name: Check code formatting
        run: ./scripts/quality/check-code-format.sh

      - name: Run Linter
        run: ./scripts/quality/linter.sh

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true
          slug: rodrigobastosv/medpal

  android:
    name: Android Build
    runs-on: ubuntu-latest
    needs: [quality_checks]
    environment: Medpal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Copy dummy Firebase options for CI
        run: cp .github/ci/firebase_options.dart lib/firebase_options.dart

      - name: Copy google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Run build_runner
        run: dart run build_runner build

      - name: Build Android App Bundle
        run: flutter build appbundle --release

  ios:
    name: iOS Build
    runs-on: macos-latest
    needs: [quality_checks]
    environment: Medpal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Copy dummy Firebase options for CI
        run: cp .github/ci/firebase_options.dart lib/firebase_options.dart

      - name: COPY GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > ios/Runner/GoogleService-Info.plist

      - name: Run build_runner
        run: dart run build_runner build

      - name: Build iOS IPA (no codesign)
        run: flutter build ipa --release --no-codesign
  web:
    name: Web Build
    runs-on: ubuntu-latest
    needs: [quality_checks]
    environment: Medpal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Copy dummy Firebase options for CI
        run: cp .github/ci/firebase_options.dart lib/firebase_options.dart

      - name: Run build_runner
        run: dart run build_runner build

      - name: Build Flutter Web
        run: flutter build web --release
